apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      component: spark-master
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      containers:
        - name: spark-master
          image: ajith154/firstimage:latest
          command:
          - /opt/spark/bin/spark-class
          - org.apache.spark.deploy.master.Master
          ports:
            - containerPort: 7077
          # Add any environment variables or volume mounts as needed
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master-service
spec:
  selector:
    component: spark-master
  ports:
    - protocol: TCP
      port: 7077
      targetPort: 7077
  type: ClusterIP

